### ISSUE TITLE
Twig globals are not always working.

### ISSUE THREAD

**Issue by VincentLanglet** [twigstan/twigstan#80]
I have a controller returning
```
return $this->render('Dashboard/Organization/settings.html.twig', [
            'organization' => $organization,
            'form' => $form->createView(),
        ]);
```

A template
```
{% extends 'Dashboard/layout.html.twig' %}

{% block footer_javascripts %}
    {{ parent() }}
{% endblock %}
```

And a layout template which use `app.user` inside the footer_javascript block.

In this situation I get `Variable 'app' does not exist.` but it should be.

As soon as I remove the footer_javascript override, there is no issue.

**Comment by VincentLanglet** [comment]
For the template inside `scope-injection` it's the same
```
/**
     * @param array{shivas_app_version: string, app: Symfony\Bridge\Twig\AppVariable, stripe_publishable_key: string, stripe_dashboard_endpoint: string, google_captcha_public: string, aws_s3_project_settings_bucket: string, cdn_domain: string} $__twigstan_globals
     * @param array{organization: App\Entity\Organization, form: Symfony\Component\Form\FormView} $context
     * @param array{} $blocks
     * @return iterable<null|scalar|\Stringable>
     */
    public function main(array $__twigstan_globals, array $context, array $blocks): iterable
    {
        // ...
    }
    // line @__main__/Dashboard/Organization/settings.html.twig:3
    /**
     * @param array{organization: App\Entity\Organization, form: Symfony\Component\Form\FormView, shivas_app_version: string, app: Symfony\Bridge\Twig\AppVariable, stripe_publishable_key: string, stripe_dashboard_endpoint: string, google_captcha_public: string, aws_s3_project_settings_bucket: string, cdn_domain: string, useGtm: bool} $context
     * @param array{} $blocks
     * @return iterable<null|scalar|\Stringable>
     */
    public function block_footer_javascripts(array $context, array $blocks): iterable
    {
        // ...
    }
    // line @__main__/Dashboard/layout.html.twig:3
    /**
     * @param array{organization: App\Entity\Organization, form: Symfony\Component\Form\FormView, shivas_app_version: string, app: Symfony\Bridge\Twig\AppVariable, stripe_publishable_key: string, stripe_dashboard_endpoint: string, google_captcha_public: string, aws_s3_project_settings_bucket: string, cdn_domain: string} $context
     * @param array{} $blocks
     * @return iterable<null|scalar|\Stringable>
     */
    public function block_page_title(array $context, array $blocks): iterable
    {
        // ...
    }
    // line @__main__/Dashboard/layout.html.twig:5
    /**
     * @param array{organization: App\Entity\Organization, form: Symfony\Component\Form\FormView, shivas_app_version: string, app: Symfony\Bridge\Twig\AppVariable, stripe_publishable_key: string, stripe_dashboard_endpoint: string, google_captcha_public: string, aws_s3_project_settings_bucket: string, cdn_domain: string, useGtm: bool} $context
     * @param array{} $blocks
     * @return iterable<null|scalar|\Stringable>
     */
    public function block_body(array $context, array $blocks): iterable
    {
        // ...
    }
    // line @__main__/Dashboard/layout.html.twig:19
    /**
     * @param array{organization: App\Entity\Organization, form: Symfony\Component\Form\FormView} $context
     * @param array{} $blocks
     * @return iterable<null|scalar|\Stringable>
     */
    public function block_container(array $context, array $blocks): iterable
    {
        // ...
    }
    // line @__main__/Dashboard/layout.html.twig:28
    /**
     * @param array{organization: App\Entity\Organization, form: Symfony\Component\Form\FormView} $context
     * @param array{} $blocks
     * @return iterable<null|scalar|\Stringable>
     */
    public function parent_block_footer_javascripts(array $context, array $blocks): iterable
    {
        // ...
```
Seems like globals are missing in parent_block and block_container...

**Comment by ruudk** [comment]
I think this might have been fixed with the latest refactors.

**Comment by VincentLanglet** [comment]
I'll give a new try soon

**Comment by ruudk** [comment]
Keep in mind TwigStan now requires PHPStan 2. Hope that's not a problem.

**Comment by ruudk** [comment]
If you use Rector, you'll have to wait till December 12 before it's released.

**Comment by VincentLanglet** [comment]
Issue is not fixed and seems related to https://github.com/twigstan/twigstan/issues/154#issuecomment-2643569484
